name: deploy-infra

run-name: ${{ github.workflow }}

on:
  workflow_dispatch:
    inputs:
      deployment_name:
        description: "Define deployment name"
        required: true
        type: string

# Requirement OIDC
permissions:
  id-token: write
  contents: read

env:
  SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  DEPLOYMENT_NAME: ${{ inputs.deployment_name }}

jobs:
  deploy:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Lint template
        working-directory: ${{ github.workspace }}/bicep
        run: |
          az bicep build --file azure.deploy.bicep

      - name: Validate template
        working-directory: ${{ github.workspace }}/bicep
        run: |
          az deployment sub validate \
            --name "$DEPLOYMENT_NAME" \
            --location westeurope \
            --template-file azure.deploy.bicep \
            --parameters "azure.deploy.parameters.json"

      - name: Deploy template
        working-directory: ${{ github.workspace }}/bicep
        run: |
          az deployment sub create \
            --name "$DEPLOYMENT_NAME" \
            --location westeurope \
            --template-file azure.deploy.bicep \
            --parameters "azure.deploy.parameters.json"
