name: destroy-infra
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      rg_hub_name:
        description: "Specify hub resource group name"
        required: true
        type: string

jobs:
  call-azure-destroy-workflow:
    uses: christosgalano/Workflow-Templates/.github/workflows/azure_destroy.yaml@main
    with:
      rg_name: ${{ inputs.rg_hub_name }}
      enable_harder_runner: false
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
