name: destroy-infra
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      deployment_name:
        description: "Specify deployment name"
        default: hub-shared-deployment
        required: true
        type: string

jobs:
  approve:
    name: Approve infrastructure tear-down
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: christosgalano
          minimum-approvals: 1
          issue-title: "Destroying infrastructure"

  call-azure-destroy-workflow:
    uses: christosgalano/github-workflows-library/.github/workflows/azure_destroy.yaml@main
    needs: approve
    with:
      deployment_name: ${{ inputs.deployment_name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
