name: gitguardian-secret-scan
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:

jobs:
  call-gitguardian-secret-scan-workflow:
    uses: christosgalano/Workflow-Templates/.github/workflows/gitguardian_secret_scan.yaml@main
    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
