name: gitguardian-scan
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:

jobs:
  scan:
    name: GitGuardian iac scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitGuardian iac scan
        uses: GitGuardian/ggshield/actions/secret@main
        with:
          args: --json
        env:
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
