name: psrule-scan
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:

jobs:
  call-psrule-scan-workflow:
    permissions:
      issues: read
      checks: write
      contents: read
      pull-requests: write
    uses: christosgalano/github-workflows-library/.github/workflows/psrule_scan.yaml@main
    with:
      template_dir: bicep
      template_prefix: azure.deploy
