name: psrule-scan
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:

jobs:
  call-psrule-scan-workflow:
    permissions:
      checks: write
      contents: read
    uses: christosgalano/Workflow-Templates/.github/workflows/psrule_scan.yaml@main
    with:
      template_dir: bicep
      template_prefix: azure.deploy
      enable_harder_runner: false
