name: scan-iac

run-name: ${{ github.workflow }}

on:
  workflow_dispatch:
    inputs:
      output_format:
        type: choice
        required: true
        description: "Define output format"
        options:
          - Sarif
          - NUnit3
env:
  OUTPUT_FORMAT: ${{ inputs.output_format }}

jobs:
  scan-and-publish:
    name: Scan Bicep
    runs-on: ubuntu-latest
    steps:
      # - name: Harden Runner
      #   uses: step-security/harden-runner@v2.0.0
      #   with:
      #     disable-sudo: true
      #     egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v3

      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: bicep/azure.deploy.bicep
          outputFilePath: bicep/azure.deploy.json

      - name: Set output file extension
        run: |
          if [ "$OUTPUT_FORMAT" == "Sarif" ]; then
            echo "FILE_EXTENSION=sarif" >> $GITHUB_ENV;
          else
            echo "FILE_EXTENSION=xml" >> $GITHUB_ENV;
          fi

      - name: Run PSRule scan
        uses: microsoft/ps-rule@v2.5.2
        with:
          modules: "PSRule.Rules.Azure"
          inputPath: bicep/azure.deploy*.json
          outputFormat: ${{ env.OUTPUT_FORMAT }}
          outputPath: results.${{ env.FILE_EXTENSION }}

      - name: Upload results as artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: scan-report
          path: results.${{ env.FILE_EXTENSION }}
          retention-days: 5

      - name: Publish Scan Report
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ always() && env.OUTPUT_FORMAT == 'NUnit3' }}
        with:
          check_name: PSRule Scan Report
          nunit_files: results.xml
