name: scan-bicep
on:
  workflow_dispatch:

jobs:
  scan-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Scan with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: bicep
          framework: bicep
          soft_fail: true
          output_format: sarif
          output_file_path: results.sarif

      - uses: actions/upload-artifact@v3
        with:
          name: scan-report
          path: results.sarif
          retention-days: 1
