name: Checkov
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ github.workspace }}/bicep
          framework: bicep
          output_format: sarif
          output_file_path: results.sarif

      - name: Show results
        run: |
          cat results.sarif
